
export const REPLACE_DEVICE_LIST = 'DEVICES/SET_DEVICE_LIST';
export const EXTEND_DEVICE_LIST = 'DEVICES/EXTEND_DEVICE_LIST';
export const REFRESH_DEVICES = 'DEVICES/REFRESH_DEVICES';
export const REQUEST_MORE_DEVICES = 'DEVICES/REQUEST_DEVICE_LIST';
export const REQUEST_MORE_DEVICES_FAILED = 'DEVICES/REQUEST_DEVICE_LIST_FAILED';