
export const LOGIN = 'AUTH/LOGIN';
export const LOGIN_REQUESTED = 'AUTH/LOGIN_REQUESTED';
export const LOGIN_FAILED = 'AUTH/LOGIN_FAILED';
export const LOGOUT = 'AUTH/LOGOUT';
export const LOGOUT_REQUESTED = 'AUTH/LOGOUT_REQUESTED';
export const REGISTER = 'AUTH/REGISTER';
export const REGISTER_REQUESTED = 'AUTH/REGISTER_REQUESTED';
export const REGISTER_FAILED = 'AUTH/REGISTER_FAILED';