export const SET_USER = '@@AUTH/SET_USER';
export const SET_TOKENS = '@@AUTH/SET_TOKENS';

export const LOGIN = {
  REQUESTED: '@@AUTH/LOGIN/REQUESTED',
  SUCCEEDED: '@@AUTH/LOGIN/SUCCEEDED',
  FAILED: '@@AUTH/LOGIN/FAILED',
};

export const REGISTER = {
  REQUESTED: '@@AUTH/REGISTER/REQUESTED',
  SUCCEEDED: '@@AUTH/REGISTER/SUCCEEDED',
  FAILED: '@@AUTH/REGISTER/FAILED',
};

export const LOGOUT = {
  REQUESTED: '@@AUTH/LOGOUT/REQUESTED',
  SUCCEEDED: '@@AUTH/LOGOUT/SUCCEEDED',
  FAILED: '@@AUTH/LOGOUT/FAILED',
};