
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_ASYNC = 'AUTH_LOGIN_ASYNC';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_REGISTER_ASYNC = 'AUTH_REGISTER_ASYNC';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';