
//// REQUESTING HOUSEHOLDS

export const REPLACE_HOUSEHOLD_LIST = `HOUSEHOLDS/SET_HOUSEHOLD_LIST`;
export const REQUEST_MORE_HOUSEHOLDS = `HOUSEHOLDS/REQUEST_MORE_HOUSEHOLDS`;
export const REQUEST_MORE_HOUSEHOLDS_FAILED = `HOUSEHOLDS/REQUEST_MORE_HOUSEHOLDS_FAILED`;

export const REFRESH_HOUSEHOLDS = `HOUSEHOLDS/REFRESH_HOUSEHOLDS`;
export const REFRESHHOUSEHOLDS_FAILED = `HOUSEHOLDS/REFRESH_HOUSEHOLDS_FAILED`;

//// REQUESTING A HOUSEHOLD

export const REQUEST_HOUSEHOLD = `HOUSEHOLDS/REQUEST_HOUSEHOLD`;
export const REQUEST_HOUSEHOLD_FAILED = `HOUSEHOLDS/REQUEST_HOUSEHOLD_FAILED`;

//// SETTING THE ACTIVE HOUSEHOLD

export const REQUEST_ACTIVE_HOUSEHOLD = `HOUSEHOLDS/REQUEST_ACTIVE_HOUSEHOLD`;
export const REQUEST_ACTIVE_HOUSEHOLD_FAILED = `HOUSEHOLDS/REQUEST_ACTIVE_HOUSEHOLD_FAILED`;
export const SET_ACTIVE_HOUSEHOLD = `HOUSEHOLDS/SET_ACTIVE_HOUSEHOLD`